### ISSUE TITLE
[프로젝트] 테스트 

### ISSUE THREAD

**Issue by inyoungbae** [djyoon956/OWL#101]
- [x] 프로젝트 생성후 모달창 reset 안됨 - @Lee-JeongEun23 
- [x] ~~프로젝트는 삭제가 안됨~~ - @Lee-JeongEun23 
- [x] 프로젝트 종료일 전에는 PM 탈퇴 불가 - @Lee-JeongEun23 
- [x] ~~팀원이 프로젝트 색상을 바꾸면 모두 바뀌지 않음~~ - @Lee-JeongEun23 
(다른 탭을 클릭했다가 다시 돌아올 때)
- [x] My Issue Progress chart에서 CLose를 Close로 바꿔주세요

**Comment by Lee-JeongEun23** [comment]
팀원이 프로젝트 색상을 바꾸는건 본인의 커스터마이징이기 때문에 모두가 바뀌면 안됩니다.
