### ISSUE TITLE
[캘린더] 테스트

### ISSUE THREAD

**Issue by inyoungbae** [djyoon956/OWL#103]
- [x] 프로젝트를 이미 지난 날짜로도 만드는게 가능 - @Lee-JeongEun23 
- [x] ex. 2/5~2/5 (하루만쓰고싶은 프로젝트) 캘린더가 안되는데.. - @Lee-JeongEun23 
- [x] 한날짜에 여러 일정이 있을 때 1 more.. 이런 식으로 표현이되는데 일정이 3개 더있는데 2more라고 뜸 (more 숫자가 다름) - @Lee-JeongEun23

**Comment by Lee-JeongEun23** [comment]
질문하기
